engines:
  rubocop:
    enabled: false
  golint:
    enabled: true
  gofmt:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  bundler-audit:
    enabled: false
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
    - "app/**"
    - "config/**"
    - "dist/**"
    - "tests/**"
exclude_paths:
- node_modules/**/*
- bower_components/**/*
- dist/**/*
- vendor/**/*
- "README.md"
