engines:
  rubocop:
    enabled: false
  golint:
    enabled: true
  gofmt:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  bundler-audit:
    enabled: false
ratings:
  paths:
    - "app/**"
    - "config/**"
    - "dist/**"
    - "tests/**"
exclude_paths:
- Documents/**/*
- bourbon/**/*
- neat/**/*
- node_modules/**/*
- bower_components/**/*
- dist/**/*
- vendor/**/*
- vendor/**/*
- "README.md"
