language: ruby
sudo: false
cache: bundler
branches:
  only:
  - master
rvm:
- 2.3.0
before_script:
- bundle exec rake db:migrate
- bundle exec rake db:seed
script:
- bundle exec rake test
addons:
  code_climate:
    repo_token: 5d52a9f74dc6c00b8b310bd793c41479d4cbab3750ef73f6ef3556f68853256d
