# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20c3cae1aaeda2f841fec7d16390f5b94a508e1182c39c47aa3145d2e1d8735a4628e82cead0f422d2960dd824b65b80e05b16bb5d5b48e7cb0c9bc5657067fc

test:
  secret_key_base: 849f18034e006d4fce558465eadca0010c26e50f7454003e5b448621d34eb912d478d2c02d0ecc9b865acb3378849a9ba1e6c72705963312acb36b55836cb9e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
